[project]
name = "pybox"
version = "0.1.1"
description = "A Python library for Explainable artificial intelligence."
authors = [{ name = "Andres B.S." }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adversarial-robustness-toolbox>=1.20.1",
    "matplotlib>=3.10.7",
    "scikit-learn>=1.7.2",
    "tqdm>=4.67.1",
]

[project.urls]
"Homepage" = "https://github.com/Andres95123/PyBox"
"Issues" = "https://github.com/Andres95123/PyBox/issues"

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "pytest>=9.0.1",
    "ruff>=0.14.7",
    "mkdocs-material",
    "mkdocstrings[python]",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "ipykernel>=7.1.0",
]

[tool.uv.workspace]
members = ["."]
