from matplotlib import pyplot as plt
import numpy as np
from art.attacks.evasion import (
    CarliniL2Method,
    DeepFool,
    FastGradientMethod,
    ProjectedGradientDescent,
)
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from typing import List, Any
from tqdm import tqdm


def plot_adversarial_img(
    adversarial_generator: Any,
    input_imgs: np.ndarray,
    methods: List[str],
    plot_diference: bool = True,
    scaler: MinMaxScaler | StandardScaler | RobustScaler | None = MinMaxScaler(),
    clipping_range: tuple[float, float] | None = (0.0, 1.0),
    max_iter: int = 10,
    ground_truth: np.ndarray | None = None,
    predict_labels: bool = False,
) -> None:
    """
    Visualize adversarial examples generated by multiple attack methods on input images.

    This function generates adversarial examples using specified attack methods and creates
    a comprehensive visualization showing the original images, adversarial variants, their
    differences, and a summary of aggregated differences across all attack methods.

    The plot layout for each row is:
    [Original Image] [Adv 1] [Diff 1] [Adv 2] [Diff 2] ... [Sum of Differences]

    Each column can display ground truth labels, predicted labels, and normalized differences.

    :param adversarial_generator: A trained classifier with predict() and loss_gradient() methods.
    :type adversarial_generator: Any
    :param input_imgs: Input images to generate adversarial examples from. Shape: (num_images, height, width, channels).
    :type input_imgs: np.ndarray
    :param methods: List of adversarial attack methods to apply. Supported: "cwL0", "cwL2", "cwLinf", "deepfool", "fgsm", "pgd".
    :type methods: List[str]
    :param plot_diference: If True, displays the normalized difference between original and adversarial images. Defaults to True.
    :type plot_diference: bool
    :param scaler: Scaler to normalize the difference maps. Options: MinMaxScaler, StandardScaler, RobustScaler, or None (no scaling). Defaults to MinMaxScaler().
    :type scaler: MinMaxScaler | StandardScaler | RobustScaler | None
    :param clipping_range: Tuple (min, max) to clip pixel values. None disables clipping. Defaults to (0.0, 1.0).
    :type clipping_range: tuple[float, float] | None
    :param max_iter: Maximum number of iterations for iterative attack methods. Defaults to 10.
    :type max_iter: int
    :param ground_truth: Ground truth labels for input images. If provided, displayed below original images. Shape: (num_images,). Defaults to None.
    :type ground_truth: np.ndarray | None
    :param predict_labels: If True, displays predicted labels below adversarial images. Defaults to False.
    :type predict_labels: bool

    :return: None. Displays the plot using matplotlib.pyplot.show().
    :rtype: None

    :raises TypeError: If adversarial_generator lacks predict() or loss_gradient() methods, or input_imgs is not a numpy array.
    :raises ValueError: If methods list contains unsupported attack types or input_imgs is empty.
    """

    # Negative type check
    if not hasattr(adversarial_generator, "predict") and not hasattr(
        adversarial_generator, "loss_gradient"
    ):
        raise TypeError(
            "adversarial_generator must be a valid classifier with predict and loss_gradient methods"
        )

    if not isinstance(input_imgs, np.ndarray):
        raise TypeError("input_imgs must be a numpy ndarray")

    if not isinstance(methods, list) or not all(
        method in ["cwL0", "cwL2", "cwLinf", "deepfool", "fgsm", "pgd"]
        for method in methods
    ):
        raise ValueError(
            "methods must be a list containing any of the following strings: "
            "'cwL0', 'cwL2', 'cwLinf', 'deepfool', 'fgsm', 'pgd'"
        )

    # Check if there are images to plot
    if input_imgs.shape[0] == 0:
        raise ValueError("input_imgs must contain at least one image to plot")

    # Plotting
    cols_per_method = 1 + (1 if plot_diference else 0)
    num_figures = 1 + len(methods) * cols_per_method + (1 if plot_diference else 0)
    fig, axes = plt.subplots(
        nrows=input_imgs.shape[0],
        ncols=num_figures,
        figsize=(3 * (num_figures), 3 * input_imgs.shape[0]),
    )
    for i in tqdm(range(input_imgs.shape[0]), desc="Generating adversarial images"):
        # Clip if necessary
        if clipping_range is not None:
            input_imgs[i] = np.clip(input_imgs[i], clipping_range[0], clipping_range[1])

        # Original
        axes[i, 0].imshow(input_imgs[i])
        axes[i, 0].set_title("Original Image")

        # Set ground truth
        if ground_truth is not None:
            axes[i, 0].set_xlabel(f"GT: {ground_truth[i]}")

        axes[i, 0].set_xticks([])
        axes[i, 0].set_yticks([])

        # Store differences for summing at the end
        all_differences = []

        for j, method in enumerate(methods):
            attack = None
            if method == "cwL0":
                attack = CarliniL2Method(
                    classifier=adversarial_generator, max_iter=max_iter, verbose=False
                )
            elif method == "cwLinf":
                attack = CarliniL2Method(
                    classifier=adversarial_generator, max_iter=max_iter, verbose=False
                )
            elif method == "cwL2":
                attack = CarliniL2Method(
                    classifier=adversarial_generator, max_iter=max_iter, verbose=False
                )
            elif method == "deepfool":
                attack = DeepFool(
                    classifier=adversarial_generator, max_iter=max_iter, verbose=False
                )
            elif method == "fgsm":
                attack = FastGradientMethod(estimator=adversarial_generator, eps=0.2)
            elif method == "pgd":
                attack = ProjectedGradientDescent(
                    estimator=adversarial_generator, eps=0.3, max_iter=max_iter
                )
            else:
                raise ValueError(f"Unsupported attack method: {method}")

            selected_img = input_imgs[i : i + 1]
            adversarial_img = attack.generate(x=selected_img)

            if clipping_range is not None:
                adversarial_img = np.clip(
                    adversarial_img, clipping_range[0], clipping_range[1]
                )

            adv_col = 1 + j * cols_per_method
            axes[i, adv_col].imshow(adversarial_img[0])
            axes[i, adv_col].set_title(f"Adversarial ({method})")

            # Predict labels if required
            if predict_labels:
                pred_label = np.argmax(
                    adversarial_generator.predict(adversarial_img), axis=1
                )[0]
                axes[i, adv_col].set_xlabel(f"Pred: {pred_label}")

            axes[i, adv_col].set_xticks([])
            axes[i, adv_col].set_yticks([])

            if plot_diference:
                difference = np.abs(adversarial_img[0] - selected_img[0])

                # Apply an scaler if added
                if scaler is not None:
                    difference = scaler.fit_transform(
                        difference.reshape(-1, 1)
                    ).reshape(difference.shape)

                if clipping_range is not None:
                    difference = np.clip(
                        difference, clipping_range[0], clipping_range[1]
                    )

                all_differences.append(difference)

                diff_col = adv_col + 1
                axes[i, diff_col].imshow(difference)
                axes[i, diff_col].set_title(f"Difference ({method})")
                axes[i, diff_col].set_xticks([])
                axes[i, diff_col].set_yticks([])

        # Add summed and clipped differences column
        if plot_diference and all_differences:
            summed_differences = np.sum(all_differences, axis=0)
            if clipping_range is not None:
                summed_differences = np.clip(
                    summed_differences, clipping_range[0], clipping_range[1]
                )

            sum_col = num_figures - 1
            axes[i, sum_col].imshow(summed_differences)
            axes[i, sum_col].set_title("Sum of Differences")
            axes[i, sum_col].set_xticks([])
            axes[i, sum_col].set_yticks([])

    plt.tight_layout()
    plt.show()
